name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [v1.11.0, latest]
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: action
        with:
          version: ${{ matrix.version }}
      - name: Check output
        shell: bash
        env:
          VERSION: ${{ steps.action.outputs.version }}
        run: |
          if [[ -n "$VERSION" ]]; then
            echo Got version output: "$VERSION"
          else
            echo Version output was empty
            exit 1
          fi
      - name: Binary exists
        shell: bash
        run: command -v helm-docs
      - name: Binary runs
        shell: bash
        run: helm-docs --version
